import {
  buildGeneralContext,
  buildTaskContext,
  formatTaskContextForInstructions,
  type ContextMode,
} from "@repograph/context-engine";
import type { RepoGraph } from "@repograph/graph-core";
import type { RepographConfig } from "@repograph/shared";

export function exportCopilotInstructions(
  graph: RepoGraph,
  config: RepographConfig,
  options?: { task?: string; mode?: ContextMode }
): string {
  const mode = options?.mode ?? "full";
  const ctx = options?.task
    ? buildTaskContext(options.task, graph, config, { mode })
    : buildGeneralContext(graph, config, mode);

  const lines = [
    "# GitHub Copilot Instructions",
    "",
    "Generated by RepoGraph Protocol. Follow these repository-specific rules.",
    "",
    formatTaskContextForInstructions(ctx, "Project Context"),
    "",
    "## Copilot behavior",
    "",
    "- Prefer edits in the listed key files only",
    "- Do not modify paths under Forbidden Edits / exclude_paths",
    "- Run related tests after changes to critical modules",
    "- Respect architecture layering rules listed above",
  ];

  return lines.join("\n");
}
